```python
class Config:
    DATABASE_URI = 'sqlite:///database.db'
    SECRET_KEY = 'your-secret-key'
    USER_DATA = 'user_data'
    WISHLIST_DATA = 'wishlist_data'
    STORE_DATA = 'store_data'
    USER_SCHEMA = 'UserSchema'
    WISHLIST_ITEM_SCHEMA = 'WishlistItemSchema'
    STORE_SCHEMA = 'StoreSchema'
    USER_PROFILE = 'user-profile'
    WISHLIST_SECTION = 'wishlist-section'
    STORE_DIRECTORY = 'store-directory'
    USER_UPDATE = 'userUpdate'
    WISHLIST_UPDATE = 'wishlistUpdate'
    STORE_UPDATE = 'storeUpdate'
    CREATE_USER = 'createUser'
    CREATE_WISHLIST_ITEM = 'createWishlistItem'
    CREATE_STORE = 'createStore'
    UPDATE_USER = 'updateUser'
    UPDATE_WISHLIST_ITEM = 'updateWishlistItem'
    UPDATE_STORE = 'updateStore'
    DELETE_USER = 'deleteUser'
    DELETE_WISHLIST_ITEM = 'deleteWishlistItem'
    DELETE_STORE = 'deleteStore'
```